### ISSUE TITLE
Can you indicate the source repo & version of wrapped code?

### ISSUE THREAD

**Issue by awwx** [deepwell/meteor-bootstrap-datepicker#1]
Thank you for wrapping a version of bootstrap-datepicker for Meteor!

Could you please include in the README what exactly was your source repo and version of the wrapped code you have in lib?  (It looks like you may have an older version or a fork of https://github.com/eternicode/bootstrap-datepicker, but there are so many versions floating around that it's hard to tell...)  Thanks!

**Comment by deepwell** [comment]
No problem and great suggestion. I've updated it to the latest release (1.1.3). I didn't realize that the link from the demo page was 6 month old version.
