### ISSUE TITLE
Bootstrap 3

### ISSUE THREAD

**Issue by mjgallag** [deepwell/meteor-bootstrap-datepicker#3]
Per https://github.com/eternicode/bootstrap-datepicker/tree/bs3 branch my understanding is support for Bootstrap 3 will come from using https://github.com/eternicode/bootstrap-datepicker/blob/bs3/css/datepicker3.css instead of https://github.com/eternicode/bootstrap-datepicker/blob/bs3/css/datepicker.css. Any ideas how to make the https://github.com/deepwell/meteor-bootstrap-datepicker/blob/master/package.js amenable to this?

**Comment by deepwell** [comment]
I don't know if you can grammatically change resources by package.js please enlighten me if it is possible.

Until Meteor revisits the package format (potentially with a solution to this), I'd just make a new atmosphere package for bootstrap3.

**Comment by mjgallag** [comment]
Ok, got it, thanks for the input. For now I'm going to follow the bootstrap-datepicker's bs3 branch on a bs3 branch of my own, forked from your package. I've simply replaced datepicker.css with the contents of datepicker3.css.

mjgallag/meteor-bootstrap-datepicker@b6f28612f07caa330021b7f294a23bf738186cd3

Once Bootstrap 3 support is officially released by bootstrap-datepicker I'll probably go ahead create my first atmosphere package :)  Unless of course there is a way to integrate it into yours at that point.

Therefore, I'll go ahead and close this issue.
